[package]
name = "hyper-client"
version = "0.1.0"
authors = ["Joseph McCormick <esmevane@gmail.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
